site_name: ksi-dev
site_url: https://ks1ksi.github.io/
repo_url: https://github.com/ks1ksi/ks1ksi.github.io

site_description: Seungil Kim's blog about computer science and software.

edit_uri: edit/main/docs/

theme:
    language: kr
    logo: content/7.png
    name: 'material'
    custom_dir: overrides
    palette:
    
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - mermaid2

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ks1ksi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/%EC%8A%B9%EC%9D%BC-%EA%B9%80-2a241711a/
    - icon: fontawesome/solid/paper-plane
      link: mailto:<ksi990302@gmail.com>

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
